### ISSUE TITLE
Not running FreeSurfer pipeline 

### ISSUE THREAD

**Issue by naailk** [josephdviviano/epitome#10]
When running the the epitome generated scripts the, freesurfer pipeline is not initiated leading to errors. I have checked the freesurfer directory and could not find a directory for the subject.

**Comment by aigoyal** [comment]
Hi Naail,

While I try to figure this out, can you please move this/create a new 'issue' in our ... cannlab's branch of this pipeline? It is located at: https://github.com/aigoyal/EPItome-xl/tree/cannlab . 

Thanks.
- aman

**Comment by josephdviviano** [comment]
Please post the error from the termjnal

**Comment by aigoyal** [comment]
Naail,

A couple of things:
1. The master script contained the epi-fsrecon command as 
`epi-fsrecon /srv/MRI/WORKING/KTEST/T1 /srv/MRI/WORKING/KTEST/proclist_150312_172340_testT1.sh` 
instead of 
`epi-fsrecon /srv/MRI/WORKING KTEST T1 /srv/MRI/WORKING/KTEST/proclist_150312_172340_testT1.sh`
2. And, the associated proclist did not contain any instance of `epi-fsrecon` at all.

I just generated a test pipeline and it worked just fine. Can you try to re-run the pipeline for this experiment/subject and see if this happens again?!

**Comment by josephdviviano** [comment]
I'm going to close this issue as I think it is resolved..
